"""Add thumbnail and applylink

Revision ID: 1385f87275d0
Revises: d1f39dd31e27
Create Date: 2023-02-19 05:15:02.572534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1385f87275d0'
down_revision = 'd1f39dd31e27'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('applylink', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('thumbnail', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'thumbnail')
    op.drop_column('jobs', 'applylink')
    # ### end Alembic commands ###
