"""Add description to jobs

Revision ID: a725b8f63dd3
Revises: 1385f87275d0
Create Date: 2023-02-19 10:06:07.799339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a725b8f63dd3'
down_revision = '1385f87275d0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'description')
    # ### end Alembic commands ###
